-- Create a table for public profiles if you want to store extra user info
create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  avatar_url text,
  updated_at timestamp with time zone,

  constraint username_length check (char_length(full_name) >= 3)
);

-- Enable RLS for profiles (safe to run multiple times)
alter table public.profiles enable row level security;

-- Policies for profiles (Drop first to avoid "policy already exists" error)
drop policy if exists "Public profiles are viewable by everyone." on profiles;
create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

drop policy if exists "Users can insert their own profile." on profiles;
create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

drop policy if exists "Users can update own profile." on profiles;
create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create a table for SOPs
create table if not exists public.sops (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  content jsonb, -- Storing the SOP structure (steps, etc.) as JSON
  tags text[],
  audio_url text, -- Path to the original recording in Storage
  is_favorite boolean default false,
  is_deleted boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for SOPs
alter table public.sops enable row level security;

-- Policies for SOPs
drop policy if exists "Users can view their own SOPs." on sops;
create policy "Users can view their own SOPs."
  on sops for select
  using ( auth.uid() = user_id );

drop policy if exists "Users can create their own SOPs." on sops;
create policy "Users can create their own SOPs."
  on sops for insert
  with check ( auth.uid() = user_id );

drop policy if exists "Users can update their own SOPs." on sops;
create policy "Users can update their own SOPs."
  on sops for update
  using ( auth.uid() = user_id );

drop policy if exists "Users can delete their own SOPs." on sops;
create policy "Users can delete their own SOPs."
  on sops for delete
  using ( auth.uid() = user_id );


-- FUNCTION & TRIGGER: Auto-create Profile on Sign Up
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url)
  values (
    new.id,
    new.email,
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'avatar_url'
  )
  -- If the profile already exists (e.g. from previous manual creation), do nothing
  on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

-- Trigger (Drop first to avoid error)
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
