-- ============================================
-- VoiceSOP — Canonical Database Schema
-- Run this in Supabase SQL Editor to set up.
-- Safe to re-run (uses IF NOT EXISTS + DROP POLICY IF EXISTS).
-- ============================================

-- =====================
-- 1. PROFILES TABLE
-- =====================
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  full_name text,
  avatar_url text,
  subscription_tier text default 'free',
  free_sop_monthly_limit integer default 3 not null,
  free_sop_monthly_used integer default 0 not null,
  free_sop_month_key text default to_char(now() at time zone 'utc', 'YYYY-MM') not null,
  free_sop_storage_limit integer default 1 not null,
  free_sop_total_limit integer default 3 not null,
  free_sop_total_used integer default 0 not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.profiles enable row level security;

drop policy if exists "Public profiles are viewable by everyone." on profiles;
drop policy if exists "Users can view own profile." on profiles;
create policy "Users can view own profile."
  on profiles for select using ( auth.uid() = id );

drop policy if exists "Users can insert their own profile." on profiles;
create policy "Users can insert their own profile."
  on profiles for insert with check ( auth.uid() = id );

drop policy if exists "Users can update own profile." on profiles;
create policy "Users can update own profile."
  on profiles for update using ( auth.uid() = id );

drop policy if exists "Users can delete own profile." on profiles;
create policy "Users can delete own profile."
  on profiles for delete using ( auth.uid() = id );

-- =====================
-- 2. SOPs TABLE
-- =====================
create table if not exists public.sops (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  title text not null default 'Untitled SOP',
  content jsonb default '{}'::jsonb,
  tags text[] default array[]::text[],
  audio_url text,
  is_favorite boolean default false,
  is_deleted boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.sops enable row level security;

drop policy if exists "Users can view their own SOPs." on sops;
create policy "Users can view their own SOPs."
  on sops for select using ( auth.uid() = user_id );

drop policy if exists "Users can create their own SOPs." on sops;
create policy "Users can create their own SOPs."
  on sops for insert with check ( auth.uid() = user_id );

drop policy if exists "Users can update their own SOPs." on sops;
create policy "Users can update their own SOPs."
  on sops for update using ( auth.uid() = user_id );

drop policy if exists "Users can delete their own SOPs." on sops;
create policy "Users can delete their own SOPs."
  on sops for delete using ( auth.uid() = user_id );

-- =====================
-- 3. UPDATED_AT TRIGGER
-- =====================
create or replace function public.handle_updated_at()
returns trigger as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$ language plpgsql;

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
  before update on public.profiles
  for each row execute function public.handle_updated_at();

drop trigger if exists set_sops_updated_at on public.sops;
create trigger set_sops_updated_at
  before update on public.sops
  for each row execute function public.handle_updated_at();

-- =====================
-- 4. AUTO-CREATE PROFILE ON SIGN UP
-- =====================
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url)
  values (
    new.id,
    new.email,
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'avatar_url'
  )
  on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- =====================
-- 5. INDEXES (Performance)
-- =====================
create index if not exists idx_sops_user_id on public.sops (user_id);
create index if not exists idx_sops_user_id_created on public.sops (user_id, created_at desc);

-- =====================
-- 6. CONSTRAINTS
-- =====================
do $$
begin
  if not exists (
    select 1 from information_schema.check_constraints
    where constraint_name = 'profiles_subscription_tier_check'
  ) then
    alter table public.profiles
      add constraint profiles_subscription_tier_check
      check (subscription_tier in ('free', 'pro'));
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from information_schema.check_constraints
    where constraint_name = 'profiles_free_sop_total_limit_check'
  ) then
    alter table public.profiles
      add constraint profiles_free_sop_total_limit_check
      check (free_sop_total_limit >= 0);
  end if;

  if not exists (
    select 1 from information_schema.check_constraints
    where constraint_name = 'profiles_free_sop_total_used_check'
  ) then
    alter table public.profiles
      add constraint profiles_free_sop_total_used_check
      check (free_sop_total_used >= 0);
  end if;

  if not exists (
    select 1 from information_schema.check_constraints
    where constraint_name = 'profiles_free_sop_monthly_limit_check'
  ) then
    alter table public.profiles
      add constraint profiles_free_sop_monthly_limit_check
      check (free_sop_monthly_limit >= 0);
  end if;

  if not exists (
    select 1 from information_schema.check_constraints
    where constraint_name = 'profiles_free_sop_monthly_used_check'
  ) then
    alter table public.profiles
      add constraint profiles_free_sop_monthly_used_check
      check (free_sop_monthly_used >= 0);
  end if;

  if not exists (
    select 1 from information_schema.check_constraints
    where constraint_name = 'profiles_free_sop_storage_limit_check'
  ) then
    alter table public.profiles
      add constraint profiles_free_sop_storage_limit_check
      check (free_sop_storage_limit >= 0);
  end if;
end $$;
