-- Create profiles table
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  full_name text,
  subscription_tier text default 'free',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for profiles
alter table public.profiles enable row level security;

-- Profiles policies
drop policy if exists "Public profiles are viewable by everyone." on public.profiles;
create policy "Public profiles are viewable by everyone." on public.profiles
  for select using (true);

drop policy if exists "Users can insert their own profile." on public.profiles;
create policy "Users can insert their own profile." on public.profiles
  for insert with check (auth.uid() = id);

drop policy if exists "Users can update own profile." on public.profiles;
create policy "Users can update own profile." on public.profiles
  for update using (auth.uid() = id);

-- Create sops table
create table if not exists public.sops (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  title text not null default 'Untitled SOP',
  audio_url text,
  content jsonb default '{}'::jsonb,
  is_deleted boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  tags text[] default array[]::text[]
);

-- Enable RLS for sops
alter table public.sops enable row level security;

-- SOPs policies
drop policy if exists "Users can view their own SOPs." on public.sops;
create policy "Users can view their own SOPs." on public.sops
  for select using (auth.uid() = user_id);

drop policy if exists "Users can insert their own SOPs." on public.sops;
create policy "Users can insert their own SOPs." on public.sops
  for insert with check (auth.uid() = user_id);

drop policy if exists "Users can update their own SOPs." on public.sops;
create policy "Users can update their own SOPs." on public.sops
  for update using (auth.uid() = user_id);

-- Storage bucket for audio
insert into storage.buckets (id, name)
values ('audio-recordings', 'audio-recordings')
on conflict do nothing;

drop policy if exists "Audio is publicly accessible." on storage.objects;
create policy "Audio is publicly accessible." on storage.objects
  for select using ( bucket_id = 'audio-recordings' );

drop policy if exists "Users can upload audio." on storage.objects;
create policy "Users can upload audio." on storage.objects
  for insert with check ( bucket_id = 'audio-recordings' and auth.uid() = owner );
