
interface SOP {
    title: string;
    content: {
        purpose: string;
        steps: Step[];
    };
    created_at: string;
}

interface Step {
    title: string;
    description: string;
    warning?: string;
    checklist?: string[];
    link?: {
        text: string;
        url: string;
    };
}

export const generateSOPMarkdown = (sop: SOP): void => {
    let md = `# ${sop.title}\n\n`;

    // Metadata
    md += `**Date:** ${new Date(sop.created_at).toLocaleDateString()}\n\n`;

    // Purpose
    if (sop.content.purpose) {
        md += `> **Purpose**\n> ${sop.content.purpose}\n\n`;
    }

    // Steps
    md += `## Steps\n\n`;

    if (sop.content.steps && sop.content.steps.length > 0) {
        sop.content.steps.forEach((step, index) => {
            md += `### ${index + 1}. ${step.title}\n`;
            md += `${step.description}\n\n`;

            if (step.warning) {
                md += `> [!WARNING]\n> ${step.warning}\n\n`;
            }

            if (step.checklist && step.checklist.length > 0) {
                step.checklist.forEach(item => {
                    md += `- [ ] ${item}\n`;
                });
                md += `\n`;
            }

            if (step.link) {
                md += `**Link:** [${step.link.text}](${step.link.url})\n\n`;
            }

            md += `---\n\n`; // Separator
        });
    } else {
        md += `*No steps recorded.*\n`;
    }

    // Footer
    md += `\n---\n*Generated by VoiceSOP*`;

    // Trigger Download
    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${sop.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
};
