interface SOPContent {
    purpose: string;
    steps: { title: string; desc: string }[];
    warnings?: string[];
    checklist?: string[];
}

export const generateMarkdown = (title: string, content: SOPContent) => {
    let md = `# ${title}\n\n`;
    md += `**Generated by VoiceSOP** • ${new Date().toLocaleDateString()}\n\n`;

    if (content.purpose) {
        md += `## Purpose\n${content.purpose}\n\n`;
    }

    if (content.warnings && content.warnings.length > 0) {
        md += `> [!WARNING]\n`;
        content.warnings.forEach(w => {
            md += `> • ${w}\n`;
        });
        md += `\n`;
    }

    md += `## Procedure Steps\n\n`;
    content.steps.forEach((step, index) => {
        md += `### Step ${index + 1}: ${step.title}\n`;
        md += `${step.desc}\n\n`;
    });

    if (content.checklist && content.checklist.length > 0) {
        md += `## Checklist\n\n`;
        content.checklist.forEach(item => {
            md += `- [ ] ${item}\n`;
        });
    }

    // Create Blob and download
    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
};
