interface SOPContent {
    purpose: string;
    steps: {
        title: string;
        description: string;
        warning?: string;
        checklist?: string[];
    }[];
    glossary?: { term: string; definition: string }[];
}

export const generateMarkdown = (title: string, content: SOPContent) => {
    let md = `# ${title}\n\n`;
    md += `**Generated by VoiceSOP** • ${new Date().toLocaleDateString()}\n\n`;

    if (content.purpose) {
        md += `## Purpose\n${content.purpose}\n\n`;
    }

    md += `## Procedure Steps\n\n`;
    content.steps.forEach((step, index) => {
        md += `### Step ${index + 1}: ${step.title}\n`;
        md += `${step.description}\n\n`;

        if (step.warning) {
            md += `> [!WARNING]\n> ${step.warning}\n\n`;
        }

        if (step.checklist && step.checklist.length > 0) {
            md += `**Checklist:**\n`;
            step.checklist.forEach(item => {
                md += `- [ ] ${item}\n`;
            });
            md += `\n`;
        }
    });

    if (content.glossary && content.glossary.length > 0) {
        md += `## Glossary\n\n`;
        content.glossary.forEach(item => {
            md += `**${item.term}**: ${item.definition}\n\n`;
        });
    }

    // Create Blob and download
    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
};
