import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface SOPContent {
    purpose: string;
    steps: {
        title: string;
        description: string;
        warning?: string;
        checklist?: string[];
    }[];
    warnings?: string[];
    checklist?: string[];
    glossary?: { term: string; definition: string }[];
}

export const generatePDF = (title: string, content: SOPContent) => {
    const doc = new jsPDF();

    // 1. Header
    doc.setFontSize(24);
    doc.setTextColor(20, 20, 20);
    doc.setFont("helvetica", "bold");
    doc.text(title, 20, 25);

    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.setFont("helvetica", "normal");
    doc.text(`Generated by VoiceSOP • ${new Date().toLocaleDateString()}`, 20, 32);

    // Line
    doc.setLineWidth(0.5);
    doc.setDrawColor(220, 220, 220);
    doc.line(20, 38, 190, 38);

    let finalY = 45;

    // 2. Purpose
    if (content.purpose) {
        doc.setFontSize(12);
        doc.setTextColor(150, 150, 150);
        doc.setFont("helvetica", "bold");
        doc.text("PURPOSE", 20, finalY);

        doc.setFontSize(11);
        doc.setTextColor(40, 40, 40);
        doc.setFont("helvetica", "normal");

        // Wrap text
        const splitPurpose = doc.splitTextToSize(content.purpose, 170);
        doc.text(splitPurpose, 20, finalY + 7);

        finalY = finalY + 7 + (splitPurpose.length * 5) + 10;
    }

    // 3. Warnings (if any)
    if (content.warnings && content.warnings.length > 0) {
        doc.setFontSize(10);
        doc.setTextColor(200, 50, 50);
        doc.setFont("helvetica", "bold");
        doc.text("WARNINGS", 20, finalY);
        finalY += 3;

        const warningBody = content.warnings.map(w => [w]);

        autoTable(doc, {
            startY: finalY,
            body: warningBody,
            theme: 'plain',
            styles: {
                fillColor: [255, 240, 240], // Light red background
                textColor: [180, 40, 40], // Dark red text
                fontSize: 10,
                cellPadding: 4,
                overflow: 'linebreak'
            },
            columnStyles: {
                0: { cellWidth: 170 }
            },
            margin: { left: 20, right: 20 }
        });

        // @ts-expect-error - jspdf-autotable adds lastAutoTable to doc
        finalY = doc.lastAutoTable.finalY + 15;
    }

    // 4. Steps Table
    doc.setFontSize(12);
    doc.setTextColor(150, 150, 150);
    doc.setFont("helvetica", "bold");
    doc.text("PROCEDURE STEPS", 20, finalY);

    finalY += 5;

    const tableBody = content.steps.map((step, index) => {
        let details = step.description || '';

        if (step.warning) {
            details += `\n\nWARNING: ${step.warning}`;
        }

        if (step.checklist && step.checklist.length > 0) {
            details += `\n\nChecklist:\n` + step.checklist.map((item: string) => `[  ]  ${item}`).join('\n');
        }

        return [
            `Step ${index + 1}`,
            step.title || '',
            details
        ];
    });

    autoTable(doc, {
        startY: finalY,
        head: [['#', 'Action', 'Details']],
        body: tableBody,
        theme: 'grid',
        headStyles: { fillColor: [25, 25, 25], textColor: 255, fontStyle: 'bold' },
        columnStyles: {
            0: { cellWidth: 20, fontStyle: 'bold', textColor: [100, 100, 100], valign: 'top' },
            1: { cellWidth: 50, fontStyle: 'bold', valign: 'top' },
            2: { cellWidth: 100, valign: 'top' } // Explicit width to prevent overflow
        },
        styles: { fontSize: 10, cellPadding: 4, overflow: 'linebreak' },
        margin: { left: 20, right: 20 }
    });

    // @ts-expect-error - jspdf-autotable adds lastAutoTable to doc
    finalY = doc.lastAutoTable.finalY + 15;

    // 5. Checklist (Global)
    if (content.checklist && content.checklist.length > 0) {
        if (finalY > 250) {
            doc.addPage();
            finalY = 20;
        }

        doc.setFontSize(12);
        doc.setTextColor(150, 150, 150);
        doc.setFont("helvetica", "bold");
        doc.text("CHECKLIST", 20, finalY);

        finalY += 8;
        doc.setFontSize(11);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(40, 40, 40);

        content.checklist.forEach((item: string) => {
            // Basic Checkbox Drawing
            doc.setDrawColor(100, 100, 100);
            doc.rect(20, finalY - 3.5, 4, 4); // Draw square

            const lines = doc.splitTextToSize(item, 160);
            doc.text(lines, 30, finalY);
            finalY += (lines.length * 6) + 2;
        });
    }

    // Footer
    const pages = doc.getNumberOfPages();
    for (let i = 1; i <= pages; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text(`Page ${i} of ${pages}`, 180, 290, { align: 'right' });
    }

    doc.save(`${title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_sop.pdf`);
};
