import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

// Define interfaces to avoid implicit any errors
interface SOPContent {
    purpose: string;
    steps: { title: string; desc: string }[];
    warnings?: string[];
    checklist?: string[];
}

export const generatePDF = (title: string, content: SOPContent) => {
    const doc = new jsPDF();

    // 1. Header
    doc.setFontSize(24);
    doc.setTextColor(20, 20, 20);
    doc.setFont("helvetica", "bold");
    doc.text(title, 20, 25);

    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.setFont("helvetica", "normal");
    doc.text(`Generated by VoiceSOP • ${new Date().toLocaleDateString()}`, 20, 32);

    // Line
    doc.setLineWidth(0.5);
    doc.setDrawColor(220, 220, 220);
    doc.line(20, 38, 190, 38);

    let finalY = 45;

    // 2. Purpose
    if (content.purpose) {
        doc.setFontSize(12);
        doc.setTextColor(150, 150, 150);
        doc.setFont("helvetica", "bold");
        doc.text("PURPOSE", 20, finalY);

        doc.setFontSize(11);
        doc.setTextColor(40, 40, 40);
        doc.setFont("helvetica", "normal");

        // Wrap text
        const splitPurpose = doc.splitTextToSize(content.purpose, 170);
        doc.text(splitPurpose, 20, finalY + 7);

        finalY = finalY + 7 + (splitPurpose.length * 5) + 10;
    }

    // 3. Warnings (if any)
    if (content.warnings && content.warnings.length > 0) {
        doc.setFillColor(255, 240, 240);
        doc.setDrawColor(255, 200, 200);

        // Calculate height roughly
        const warningLines = content.warnings.map(w => `• ${w}`);
        const warningBlockHeight = (warningLines.length * 6) + 10;

        doc.roundedRect(20, finalY, 170, warningBlockHeight, 2, 2, 'FD');

        doc.setFontSize(10);
        doc.setTextColor(200, 50, 50);
        doc.setFont("helvetica", "bold");
        doc.text("WARNINGS", 25, finalY + 8);

        doc.setFont("helvetica", "normal");
        doc.setTextColor(150, 40, 40);

        let warnY = finalY + 14;
        content.warnings.forEach(w => {
            const lines = doc.splitTextToSize(`• ${w}`, 160);
            doc.text(lines, 25, warnY);
            warnY += (lines.length * 5);
        });

        finalY = warnY + 10;
    }

    // 4. Steps Table
    doc.setFontSize(12);
    doc.setTextColor(150, 150, 150);
    doc.setFont("helvetica", "bold");
    doc.text("PROCEDURE STEPS", 20, finalY);

    finalY += 5;

    const tableBody = content.steps.map((step, index) => [
        `Step ${index + 1}`,
        step.title,
        step.desc
    ]);

    autoTable(doc, {
        startY: finalY,
        head: [['#', 'Action', 'Details']],
        body: tableBody,
        theme: 'grid',
        headStyles: { fillColor: [25, 25, 25], textColor: 255, fontStyle: 'bold' },
        columnStyles: {
            0: { cellWidth: 20, fontStyle: 'bold', textColor: [100, 100, 100] },
            1: { cellWidth: 50, fontStyle: 'bold' },
            2: { cellWidth: 'auto' }
        },
        styles: { fontSize: 10, cellPadding: 4, overflow: 'linebreak' },
        margin: { left: 20, right: 20 }
    });

    // Get Y after table
    // @ts-ignore - autoTable adds lastAutoTable to doc object but ts doesn't know
    finalY = doc.lastAutoTable.finalY + 15;

    // 5. Checklist
    if (content.checklist && content.checklist.length > 0) {
        // Check for page break
        if (finalY > 250) {
            doc.addPage();
            finalY = 20;
        }

        doc.setFontSize(12);
        doc.setTextColor(150, 150, 150);
        doc.setFont("helvetica", "bold");
        doc.text("CHECKLIST", 20, finalY);

        finalY += 8;
        doc.setFontSize(11);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(40, 40, 40);

        content.checklist.forEach(item => {
            // Draw checkbox square
            doc.setDrawColor(100, 100, 100);
            doc.rect(20, finalY - 3, 4, 4);

            doc.text(item, 30, finalY);
            finalY += 7;
        });
    }

    // Footer
    const pageCount = doc.internal.types.number.pageCount; // Incorrect usage in types sometimes
    // Simplest footer
    const pages = doc.getNumberOfPages();
    for (let i = 1; i <= pages; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text(`Page ${i} of ${pages}`, 180, 290, { align: 'right' });
    }

    doc.save(`${title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_sop.pdf`);
};
