import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface SOPData {
    title: string;
    content: {
        purpose?: string;
        steps: Array<{
            title: string;
            description: string;
            warning?: string;
            checklist?: string[];
        }>;
    };
    created_at: string;
}

export const generateSOPPDF = (sop: SOPData) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;
    const margin = 20;

    // Header
    doc.setFontSize(22);
    doc.setTextColor(40, 40, 40);
    doc.text(sop.title, margin, 30);

    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    const dateStr = new Date(sop.created_at).toLocaleDateString();
    doc.text(`Created: ${dateStr}`, margin, 38);

    doc.setDrawColor(200, 200, 200);
    doc.line(margin, 42, pageWidth - margin, 42);

    let yPos = 55;

    // Purpose
    if (sop.content.purpose) {
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(60, 60, 60);
        doc.text('Purpose', margin, yPos);
        yPos += 7;

        doc.setFontSize(11);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(80, 80, 80);

        // Split text to fit page
        const purposeLines = doc.splitTextToSize(sop.content.purpose, pageWidth - (margin * 2));
        doc.text(purposeLines, margin, yPos);

        yPos += (purposeLines.length * 7) + 10;
    }

    // Steps
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(40, 40, 40);
    doc.text('Procedure', margin, yPos);
    yPos += 10;

    sop.content.steps.forEach((step, index) => {
        // Page break check
        if (yPos > doc.internal.pageSize.height - 40) {
            doc.addPage();
            yPos = 30;
        }

        // Step Title
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(0, 0, 0);
        doc.text(`${index + 1}. ${step.title}`, margin, yPos);
        yPos += 7;

        // Description
        doc.setFontSize(11);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(60, 60, 60);
        const descLines = doc.splitTextToSize(step.description, pageWidth - (margin * 2) - 10);
        doc.text(descLines, margin + 5, yPos);
        yPos += (descLines.length * 6) + 4;

        // Warning
        if (step.warning) {
            // Basic styling for warning
            doc.setTextColor(200, 60, 60); // Red
            doc.setFontSize(10);
            doc.text(`Warning: ${step.warning}`, margin + 5, yPos);
            yPos += 6;
        }

        // Checklist
        if (step.checklist && step.checklist.length > 0) {
            doc.setTextColor(40, 40, 40);
            doc.setFontSize(10);
            step.checklist.forEach(item => {
                doc.text(`o  ${item}`, margin + 8, yPos);
                yPos += 5;
            });
            yPos += 2;
        }

        yPos += 8; // Spacing between steps
    });

    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(9);
        doc.setTextColor(150, 150, 150);
        doc.text(`Generated by VoiceSOP - Page ${i} of ${pageCount}`, pageWidth / 2, doc.internal.pageSize.height - 10, { align: 'center' });
    }

    doc.save(`${sop.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_sop.pdf`);
};
