import Footer from '@/components/sections/Footer';
import Link from 'next/link';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Privacy Policy - VoiceSOP',
    description: 'VoiceSOP Privacy Policy. Learn how we collect, use, and protect your data.',
};

export default function PrivacyPage() {
    return (
        <main className="relative min-h-screen w-full bg-warm-grey overflow-hidden">
            <div className="pt-24 sm:pt-32 pb-16 px-4 sm:px-6">
                <div className="max-w-3xl mx-auto">
                    {/* Header */}
                    <div className="mb-12">
                        <p className="text-brand-red text-sm font-medium uppercase tracking-widest mb-3">Legal</p>
                        <h1 className="text-4xl sm:text-5xl font-serif italic text-off-black mb-4">Privacy Policy</h1>
                        <p className="text-gray-500 text-sm">Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>
                    </div>

                    {/* Content */}
                    <div className="prose prose-gray max-w-none space-y-8">
                        <section>
                            <h2 className="text-2xl font-serif italic text-off-black mb-3">1. Introduction</h2>
                            <p className="text-gray-600 leading-relaxed">
                                VoiceSOP (&quot;we&quot;, &quot;our&quot;, or &quot;us&quot;) is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our web application and related services (collectively, the &quot;Service&quot;).
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-serif italic text-off-black mb-3">2. Information We Collect</h2>
                            <h3 className="text-lg font-bold text-off-black mb-2">2.1 Personal Information</h3>
                            <p className="text-gray-600 leading-relaxed mb-3">When you create an account, we collect:</p>
                            <ul className="list-disc pl-6 text-gray-600 space-y-1">
                                <li>Email address</li>
                                <li>Name (if provided via OAuth)</li>
                                <li>Authentication tokens (managed securely by Supabase)</li>
                            </ul>

                            <h3 className="text-lg font-bold text-off-black mt-4 mb-2">2.2 Audio & Content Data</h3>
                            <p className="text-gray-600 leading-relaxed mb-3">When you use the Service, we process:</p>
                            <ul className="list-disc pl-6 text-gray-600 space-y-1">
                                <li>Audio recordings you upload or record</li>
                                <li>Transcribed text generated from your audio</li>
                                <li>Standard Operating Procedures (SOPs) generated by our AI</li>
                            </ul>

                            <h3 className="text-lg font-bold text-off-black mt-4 mb-2">2.3 Usage Data</h3>
                            <p className="text-gray-600 leading-relaxed">
                                We automatically collect certain information about your device and usage patterns, including IP address (for rate limiting), browser type, and pages visited.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-serif italic text-off-black mb-3">3. How We Use Your Information</h2>
                            <ul className="list-disc pl-6 text-gray-600 space-y-2">
                                <li><strong>To provide the Service:</strong> Processing audio, generating transcriptions, and creating SOPs.</li>
                                <li><strong>To manage your account:</strong> Authentication, subscription management, and usage tracking.</li>
                                <li><strong>To improve the Service:</strong> Analyzing usage patterns to enhance features and performance.</li>
                                <li><strong>To communicate:</strong> Sending transactional emails related to your account.</li>
                                <li><strong>To ensure security:</strong> Rate limiting, fraud prevention, and abuse detection.</li>
                            </ul>
                        </section>

                        <section>
                            <h2 className="text-2xl font-serif italic text-off-black mb-3">4. Third-Party Services</h2>
                            <p className="text-gray-600 leading-relaxed mb-3">We use the following third-party services to operate VoiceSOP:</p>
                            <ul className="list-disc pl-6 text-gray-600 space-y-2">
                                <li><strong>Supabase:</strong> Authentication, database, and file storage.</li>
                                <li><strong>Groq:</strong> Audio transcription (Whisper) and AI text generation.</li>
                                <li><strong>Google (Gemini):</strong> AI text generation for Pro users.</li>
                                <li><strong>Upstash:</strong> Redis-based rate limiting.</li>
                                <li><strong>Razorpay:</strong> Payment processing for subscriptions.</li>
                            </ul>
                            <p className="text-gray-600 leading-relaxed mt-3">
                                Each service processes data in accordance with their own privacy policies. We recommend reviewing their policies for details on their data practices.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-serif italic text-off-black mb-3">5. Data Retention</h2>
                            <p className="text-gray-600 leading-relaxed">
                                Your audio files and generated SOPs are stored in your account until you delete them. When you delete an SOP, the associated audio file and all generated content are permanently removed from our storage. Upon account deletion, all your data is permanently erased.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-serif italic text-off-black mb-3">6. Data Security</h2>
                            <p className="text-gray-600 leading-relaxed">
                                We implement industry-standard security measures including encrypted data transmission (TLS/SSL), secure authentication via Supabase, Row Level Security (RLS) policies ensuring users can only access their own data, and rate limiting to prevent abuse.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-serif italic text-off-black mb-3">7. Your Rights</h2>
                            <p className="text-gray-600 leading-relaxed mb-3">You have the right to:</p>
                            <ul className="list-disc pl-6 text-gray-600 space-y-1">
                                <li>Access your personal data</li>
                                <li>Delete your account and all associated data</li>
                                <li>Export your generated SOPs</li>
                                <li>Opt out of non-essential communications</li>
                            </ul>
                        </section>

                        <section>
                            <h2 className="text-2xl font-serif italic text-off-black mb-3">8. Children&apos;s Privacy</h2>
                            <p className="text-gray-600 leading-relaxed">
                                VoiceSOP is not intended for use by individuals under the age of 18. We do not knowingly collect any personal information from children.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-serif italic text-off-black mb-3">9. Changes to This Policy</h2>
                            <p className="text-gray-600 leading-relaxed">
                                We may update this Privacy Policy from time to time. We will notify you of any significant changes by posting a notice within the Service. Your continued use of VoiceSOP after changes are posted constitutes your acceptance of the updated policy.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-serif italic text-off-black mb-3">10. Contact Us</h2>
                            <p className="text-gray-600 leading-relaxed">
                                If you have any questions or concerns about this Privacy Policy, please contact us at{' '}
                                <Link href="/contact" className="text-brand-red hover:underline">our contact page</Link>.
                            </p>
                        </section>
                    </div>
                </div>
            </div>
            <Footer />
        </main>
    );
}
